### ISSUE TITLE
Question: about shader exported output

### ISSUE THREAD

**Issue by sugarico** [spacehamster/UtinyRipperExporter#2]
Hi,

I used the ripper of your and the output only surf function with default output, same for all shader files in a game assets

![03](https://user-images.githubusercontent.com/51503947/66737915-68f6fc00-ee97-11e9-8505-a49e7aac05da.png)

but when I use ripper tool of mafaca, the output here

![04](https://user-images.githubusercontent.com/51503947/66737962-875cf780-ee97-11e9-9094-6f7f775735bd.png)

I saw the HLSLccWrapper from your code, I hope that it could decompile shader to readable with unity coder like me but the output just same for all file and didnt have vert and frag functions.

**Comment by spacehamster** [comment]
By default it extracts dummy shaders because most games use HLSL, and there currently isn't a good way of getting those into Unity's ShaderLab format. To extract GLES shaders normally, run with the arguments `--shadermode Default`. HLSLccWrapper is for converting HLSL shaders to GLSL disassembly, the code in your screenshot looks plain text GLES shader.

**Comment by sugarico** [comment]
I changed the --shardermode param to Default and got the same output with ripper of mafaca, thanks for your reply.
